services:
  bundle: &bundle
    env_file: .env
    stdin_open: true
    tty: true
    build: .
    entrypoint: bundle
    command: check
    volumes:
      - .:/usr/src/app:delegated
      - bundle:/usr/local/bundle:delegated
      - ~/Projects:/local

  app:
    <<: *bundle
    command: exec rails server -b 0.0.0.0
    ports:
      - 3000:3000

  rspec:
    <<: *bundle
    entrypoint: bundle exec rspec
    command: --version

  protoc:
    build: .
    entrypoint: bundle
    command: |
      exec grpc_tools_ruby_protoc
      -I ./lib/protos --ruby_out=./lib/protobuf --twirp_ruby_out=./lib/protobuf
      ./lib/protos/things.proto
    volumes:
      - .:/usr/src/app:delegated
      - bundle:/usr/local/bundle:delegated

volumes:
  bundle: {}
