# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: things.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("things.proto", :syntax => :proto3) do
    add_message "ThingParams" do
      optional :id, :int32, 1
      optional :name, :string, 2
    end
    add_message "ThingFilter" do
      optional :name, :string, 1
    end
    add_message "ThingResponse" do
      optional :id, :int32, 1
      optional :name, :string, 2
    end
    add_message "ThingList" do
      repeated :things, :message, 1, "ThingResponse"
    end
  end
end

ThingParams = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThingParams").msgclass
ThingFilter = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThingFilter").msgclass
ThingResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThingResponse").msgclass
ThingList = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ThingList").msgclass
