# Code generated by protoc-gen-twirp_ruby 1.6.0, DO NOT EDIT.
require 'twirp'
require_relative 'things_pb.rb'

class ThingsService < Twirp::Service
  service 'Things'
  rpc :Create, ThingParams, ThingResponse, :ruby_method => :create
  rpc :Show, ThingParams, ThingResponse, :ruby_method => :show
  rpc :Index, ThingFilter, ThingList, :ruby_method => :index
  rpc :Update, ThingParams, ThingResponse, :ruby_method => :update
  rpc :Destroy, ThingParams, ThingResponse, :ruby_method => :destroy
end

class ThingsClient < Twirp::Client
  client_for ThingsService
end
